# Builds the docs and tests that they work correctly
# Based on https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Docs

on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  build:
    name: Build docs

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup and Install
      uses: ./.github/actions/setup-and-install
    - name: List dependencies
      shell: bash
      run: pip list
    - name: Build docs
      uses: ./.github/actions/build-docs


  linkcheck:
    name: Check links

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Setup and Install
      uses: ./.github/actions/setup-and-install
    - name: Run Linkcheck
      run: make linkcheck


  pre-commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Dependencies
      uses: ./.github/actions/setup-and-install
    - name: Run Main Pre-Commit Hooks
      uses: pre-commit/action@v2.0.2
